spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: restfullapi
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/db_local
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: qa
  application:
    name: restfullapiQA
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/db_qa
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true